# -*- coding: utf-8 -*-
"""mapper_reducer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196ZtqiwR-Kn90TPi5l0_bzgb6tWZkKel

**NAME:** Shreyasi Kar

**COURSE:** Distributed Computing and Big Data

**ROLL NO:** MDS202533

**ASSIGNMENT:** Analyzing Publication Metadata via RPC
"""

# =========================
# IMPORTS
# =========================
import requests
import time
from multiprocessing import Pool, cpu_count
from collections import Counter
import re

# =========================
# CONFIG
# =========================
BASE_URL = "http://72.60.221.150:8080"
STUDENT_ID = "MDS202533"

# =========================
# LOGIN FUNCTION
# =========================
def get_secret_key(student_id):
    url = BASE_URL + "/login"
    response = requests.post(url, json={"student_id": student_id}, timeout=5)
    return response.json()["secret_key"]

# =========================
# FETCH TITLE (STABLE)
# =========================
def fetch_title(secret_key, filename):
    url = BASE_URL + "/lookup"
    payload = {
        "secret_key": secret_key,
        "filename": filename
    }

    while True:  # keep retrying until success
        try:
            res = requests.post(url, json=payload, timeout=3)

            if res.status_code == 200:
                return res.json().get("title", None)

            elif res.status_code == 429:
                time.sleep(0.3)  # wait and retry

            else:
                return None

        except requests.exceptions.RequestException:
            time.sleep(0.3)

# =========================
# FIRST WORD (CORRECT)
# =========================
def get_first_word(title):
    if not title:
        return None

    title = title.strip()
    first_word = title.split()[0]

    # remove punctuation at edges
    first_word = re.sub(r'^[^a-zA-Z]+|[^a-zA-Z]+$', '', first_word)

    return first_word.capitalize()

# =========================
# MAP FUNCTION
# =========================
def mapper(args):
    file_chunk, secret_key = args
    counter = Counter()

    for filename in file_chunk:
        title = fetch_title(secret_key, filename)

        time.sleep(0.02)

        word = get_first_word(title)

        if word:
            counter[word] += 1

    return counter

# =========================
# SPLIT WORK
# =========================
def chunkify(lst, n):
    return [lst[i::n] for i in range(n)]

# =========================
# VERIFY FUNCTION
# =========================
def verify(top_10, secret_key):
    url = BASE_URL + "/verify"
    payload = {
        "secret_key": secret_key,
        "top_10": top_10
    }

    res = requests.post(url, json=payload, timeout=5)

    print("\nVerification Result:")
    print(res.json())

# =========================
# MAIN EXECUTION
# =========================
if __name__ == "__main__":

    print("Starting...")

    SECRET_KEY = get_secret_key(STUDENT_ID)

    files = [f"pub_{i}.txt" for i in range(1000)]

    num_workers = cpu_count()
    print(f"Using {num_workers} workers...")

    chunks = chunkify(files, num_workers)
    tasks = [(chunk, SECRET_KEY) for chunk in chunks]

    with Pool(num_workers) as pool:
        results = pool.map(mapper, tasks)

    print("Mapping done. Reducing...")

    final_counter = Counter()
    for c in results:
        final_counter.update(c)

    # Deterministic sorting
    sorted_words = sorted(final_counter.items(), key=lambda x: (-x[1], x[0]))
    top_10 = [word for word, _ in sorted_words[:10]]

    print("\nTop 10 First Words:")
    print(top_10)

    verify(top_10, SECRET_KEY)